### ISSUE TITLE
Design staff management page (Prototype 2)

### ISSUE THREAD

**Issue by MarshallCN** [EADG6/TrainTickets#10]
- Use wire-frames (url: https://www.draw.io/)
- A table shows all staff information (check following picture, columns name should refers to our database)
![image](https://cloud.githubusercontent.com/assets/16070638/25695349/4d9c77c2-30e5-11e7-91f2-cbb23076fcf3.png)
 - A form to add new staff (参考下图，具体输入框应对照数据库的staff表)
![](https://cloud.githubusercontent.com/assets/16070638/25695716/c7c6b87c-30e6-11e7-8dd3-5b53258811d4.png)

**Comment by leo-lizhuoxuan** [comment]
new staff page 
![untitled diagram](https://cloud.githubusercontent.com/assets/26318938/26297811/28016344-3f07-11e7-9fbd-fd969bd1c414.png)

**Comment by leo-lizhuoxuan** [comment]
All Staff

![untitled diagram 1](https://cloud.githubusercontent.com/assets/26318938/26299509/a698e9b0-3f0d-11e7-85a4-ea65e5095dc5.png)

**Comment by leo-lizhuoxuan** [comment]
Role Management
![untitled diagram 2](https://cloud.githubusercontent.com/assets/26318938/26299894/08136868-3f0f-11e7-8839-49fcc073f8d6.png)
