### ISSUE TITLE
Design Selling ticket user interface (Prototype 1)

### ISSUE THREAD

**Issue by MarshallCN** [EADG6/TrainTickets#2]
- use wire-frames (url: https://www.draw.io/)
- Functions & sub-page:
  - "Add new ticket" page
    - Input: Start/End City (selection)
    - Input: Start/End Time
    - Input: Ticket Date
    - Input: Seat Level (selection)
    - Input: Customer Phone (As their unique identity) 
    - Output: Ticket price, ticket's start/end city/time, cus, seats info
    - Output: Error condition: 
          - Cannot found user (go to create user page)
          - No train between the cities
          - No train in that day
          - No remaining seats of a certain level

**Comment by CaryTian** [comment]
- This is the ticket selling page:
![](https://trello-attachments.s3.amazonaws.com/5839e46fbe06acdaa1cb2471/590b54383cd86b6bd360e97f/f8ab77582845f36c35c7716fcd42920a/ticket_sell1.png)
- this is the page with error state:
![](https://trello-attachments.s3.amazonaws.com/5839e46fbe06acdaa1cb2471/590b54383cd86b6bd360e97f/20a26f8285e7c88d3144dc7e0ca24d84/ticket_sell2.png)
- [ticket_sell.txt](https://trello-attachments.s3.amazonaws.com/5839e46fbe06acdaa1cb2471/590b54383cd86b6bd360e97f/daaba25977666cbaa97bcae4bcd28e0f/ticket_sell.txt)
