### ISSUE TITLE
Design ticket management page interface (Prototype 1)

### ISSUE THREAD

**Issue by MarshallCN** [EADG6/TrainTickets#3]
* use wire-frames  (url: https://www.draw.io/)
* Show all the tickets (2 tier drop-down menu + pop up table)
  - use ***icon*** to show edit functions (check following picture)
     ![image](https://cloud.githubusercontent.com/assets/16070638/25694061/2fe52220-30df-11e7-80f7-e9379e907ee4.png)

**Comment by qq398935137** [comment]
ticket management page interface 
![ticket management page interface prototype 1]
![ticket management page interface prototype 1 1](https://cloud.githubusercontent.com/assets/19308817/25793735/699a3158-3400-11e7-9e3f-805308ec6444.png)

**Comment by MarshallCN** [comment]
日期你是怎么表示的？
应该是第一层城市，第二层日期吧，第三层一个弹出框才是具体的车票

**Comment by qq398935137** [comment]
@MarshallCN 第二层只有日期？那是要弹多少天的出来，最近5天？弹出框需要单独做不

**Comment by MarshallCN** [comment]
有多少弹出多少，如果太多就把数据分页，弹出框单独做个页面就行，前两层一个页面
