### ISSUE TITLE
Design Train Management Page (Prototype 1)

### ISSUE THREAD

**Issue by MarshallCN** [EADG6/TrainTickets#5]
* use wire-frames (url: https://www.draw.io/)
- A table shows all trains 一个表格来显示所有车次
- Add new train form 添加车次的表单
    - Input: Train name (K886)
    - Input: Train type
    - Input: Start/End city (Selection)
    - Input: Start/End Time (只有时刻没有日期)
    - Input: Seats Level/ Seats Number (列车有哪几种座位类型，分别多少个位置，注意这里和train_type有关联，比如train_type为快速车的是没有卧铺的)
- Edit train (重用上面的表单来修改车次，实际实施中只需用JS调整几个“创建”表单中的input，就能将其改为“修改”表单，interface设计上直接复制即可)

**Comment by leo-lizhuoxuan** [comment]
![default](https://cloud.githubusercontent.com/assets/26318938/25700940/98d98948-30fc-11e7-98ee-d3fd3b219c42.png)
![trains manage](https://cloud.githubusercontent.com/assets/16070638/25702255/b96700ea-3102-11e7-9493-e164e084adb8.png)

This is "Manage Trains Page" first design
