### ISSUE TITLE
Design customer management page (Prototype 1)

### ISSUE THREAD

**Issue by MarshallCN** [EADG6/TrainTickets#6]
- Use wire-frames (url: https://www.draw.io/)
- A table shows all customers information (check following picture)
    - Information type:  first name, last name, sex, birthday, phone  将下图中的列名改为这几个即可
![image](https://cloud.githubusercontent.com/assets/16070638/25695349/4d9c77c2-30e5-11e7-91f2-cbb23076fcf3.png)
- A form to ***add new customer*** （一个表单，input输入框还是上面Information type中的那几个，参考下图）
![image](https://cloud.githubusercontent.com/assets/16070638/25695716/c7c6b87c-30e6-11e7-8dd3-5b53258811d4.png)

**Comment by BreakingAir** [comment]
- add new customer
![add new customer](https://cloud.githubusercontent.com/assets/26341284/25733249/dc44e0e6-3189-11e7-9eb8-3b54353d77f9.png)
- customer management
![download](https://cloud.githubusercontent.com/assets/26341284/25733272/0662cabe-318a-11e7-9808-891698f46874.png)
